myApp.directive 'dirFieldDate', (directiveService, $filter, generateId) ->
    restrict: 'E'
    scope: directiveService.autoScope(ngInfo: '=')
    templateUrl: '/assets/js/directive/field/dirFieldDate/template.html'
    replace: true
    transclude: true
    compile: ->
        pre: (scope) ->
            directiveService.autoScopeImpl scope
            #generate an id for the calendar plugin
            scope.id = generateId.generate()
            scope.idHtag = '#' + scope.id
        post: (scope) ->
            directiveService.autoScopeImpl scope

            #params
            scope.result = null

            #watch  the result variable, generated by the calendar plugin
            scope.$watch 'result', (n, o) ->
                if n != o
                    if scope.result?
                        scope.getInfo().field[scope.getInfo().fieldName] = scope.result.getTime()
                    else
                        scope.getInfo().field[scope.getInfo().fieldName] = null
                    scope.isValid()
                    if scope.getInfo().minimalDelay == 'day'
                        scope.resultFormated = $filter('date')(scope.result, 'yyyy-MM-dd')
                    else
                        scope.resultFormated = $filter('date')(scope.result, 'yyyy-MM-dd HH:mm')

            #if the field is active ?
            scope.isActive = ->
                return !(scope.getInfo().active? and scope.getInfo().active() == false)

            # watch the value of the field to test the validity
            scope.$watch 'getInfo().field[getInfo().fieldName]', (n, o) ->
                if n != o
                    if scope.getInfo().field[scope.getInfo().fieldName]?
                        return scope.result = new Date(Number(scope.getInfo().field[scope.getInfo().fieldName]))
                    scope.isValid()

            # if the field is valid ?
            scope.isValid = ->
                isValid = undefined
                if scope.getInfo().disabled == true or scope.isActive() == false
                    scope.getInfo().isValid = true
                    return
                isValid = true
                if !scope.getInfo().field[scope.getInfo().fieldName]?
                    isValid = false
                if scope.getInfo().validationFct?
                    isValid = isValid and scope.getInfo().validationFct()
                scope.getInfo().isValid = isValid


            # display the error message
            scope.displayError = ->
                if scope.getInfo().isValid == false and scope.getInfo().firstAttempt == false
                    return true
                return false

            # initialization
            # initialize the first value
            if scope.getInfo().field[scope.getInfo().fieldName]?
                scope.result = new Date(Number(scope.getInfo().field[scope.getInfo().fieldName]))
                if scope.getInfo().minimalDelay == 'day'
                    scope.resultFormated = $filter('date')(scope.result, 'yyyy-MM-dd')
                else
                    scope.resultFormated = $filter('date')(scope.result, 'yyyy-MM-dd HH:mm')

            #test the validity of the field
            scope.isValid()